### ISSUE TITLE
Translation support in the weather skin

### ISSUE THREAD

**Issue by flyinghyrax** [flyinghyrax/Elementary#17]
When re-writing the weather skin, I have (so far) left out all the substitution entries to support translations.

I have tried using my existing substitute settings on the measures that parse an icon code from weather.com, and compared this to the text parsed from weather.com... the translated text is less descriptive than the text straight from weather.com.

I wonder if the feed contents can be localized when requesting them?

The point is, I'm not sure how to approach translation yet. Ideally, I would like to avoid having to request new translation files. It's a pain to manage that process, and I'm not going to have time in the future. So I might just leave them off altogether.

**Comment by eclectic-tech** [comment]
Happy to see you found some time (a precious commodity, for sure!)... I utilized the language capabilities from the WXDATA feed for simple translations... not sure if you can incorporate it, but here is an example, my illustroSimpleWeather skin: http://eclectic-tech.deviantart.com/art/illustroSimpleWeather-540403575

**Comment by flyinghyrax** [comment]
Thank you @eclectic-tech ! Your skin is a very helpful example. I'm very happy to see that the WXData feed can return localized results; that saves an enormous amount of work. The bulk of the translation work was the weather conditions, so I will be able to re-use much of the old translation files I already have, and it should be easier for users to contribute new translations if they desire.
