### ISSUE TITLE
Context menu unit toggle in the weather skin

### ISSUE THREAD

**Issue by flyinghyrax** [flyinghyrax/Elementary#18]
I'd like to implement a context menu entry that toggles the weather skin between English and Metric units. This seems like it would be consistent with the other skins, re-written so far... though people are not going to need to toggle that setting often.

**Comment by eclectic-tech** [comment]
Simple skin that has this feature. You are welcome to use it, if it is of any use for you... 
http://eclectic-tech.deviantart.com/art/illustroSimpleWeather-540403575
