### ISSUE TITLE
Spotify player not enough text height

### ISSUE THREAD

**Issue by jogerj** [flyinghyrax/Elementary#25]
![image](https://user-images.githubusercontent.com/30559735/28749248-5e454bce-74c1-11e7-82ef-ee2899900baa.png)
Some letters like "g" are cut off because of not enough space. 
"ClipStringH=41" needs to be increased to at least "ClipStringH=45"
As for the other media player I don't know as I didn't test it.

**Comment by flyinghyrax** [comment]
Thanks @jogerj ! Good catch. It's likely a problem for both player skins; I'll be sure to take a look at the NowPlaying version as well.

**Comment by flyinghyrax** [comment]
I think part of the problem in the screenshot is the font; it looks like you're missing Century Gothic so Rainmeter is rendering the track info in Arial instead, which has a larger descender height.

I haven't been including Century Gothic in the .rmskin packages for licensing reasons, but I've always wondered whether I should just include the font anyway... It's included with Microsoft Office products, I think, but it _is_ possible to find a download for the font online with a little searching.

That said, even in Century Gothic the 'g' is losing a pixel or two, so I'm going to increase the `ClipStringH` anyway.
